apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: bitnami/kaniko:1.23.2
      args:
        - "--dockerfile reverse-dns-lookup.Dockerfile"
        - "--context dir"
        - "--destination alexmartgon/jenkins-reverse-dns-lookup:0.0.1 "
      volumeMounts:
        - name: docker-access-key
          mountPath: /kaniko/.docker
      env:
      - name: GIT_USERNAME
        valueFrom:
          secretKeyRef:
            name: git-access-key-alexmartgon
            key: USER
      - name: GIT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: git-access-key-alexmartgon
            key: TOKEN
  restartPolicy: Never
  volumes:
    - name: docker-access-key
      secret:
        secretName: docker-access-key